### ISSUE TITLE
菜单栏图标颜色不随 Catalina 的深色/浅色模式自动切换而自动改变

### ISSUE THREAD

**Issue by zerychao** [wzdnzd/ShadowsocksX-NG-R#15]
你好，

使用过程中，发现菜单栏图标颜色不会随着 Catalina 的深色/浅色模式**自动切换**而自动改变，而要手动做出某个操作（如开启/关闭代理、显示/隐藏网速等）才会改变。但记忆中使用更早的版本时此问题并不存在，是否是个例？另外，ShadowsocksX-NG-R8 同样存在这个问题，希望能够完善。

谢谢。

**Comment by paradiseduo** [comment]
> 你好，
> 
> 使用过程中，发现菜单栏图标颜色不会随着 Catalina 的深色/浅色模式**自动切换**而自动改变，而要手动做出某个操作（如开启/关闭代理、显示/隐藏网速等）才会改变。但记忆中使用更早的版本时此问题并不存在，是否是个例？另外，ShadowsocksX-NG-R8 同样存在这个问题，希望能够完善。
> 
> 谢谢。

在最新的代码中已经修了这个问题
