### ISSUE TITLE
能否考虑加入tls1.2_ticket_fastauth混淆？

### ISSUE THREAD

**Issue by redapple0204** [wzdnzd/ShadowsocksX-NG-R#16]
该版本混淆不会等待服务器回应，因此能够降低延迟。
谢谢！

**Comment by redapple0204** [comment]
或者说，在订阅中如果遇到使用tls1.2_ticket_fastauth混淆的服务器，能否自动切换到tls1.2_ticket_auth混淆。
谢谢！

**Comment by paradiseduo** [comment]
已经加了

**Comment by redapple0204** [comment]
@paradiseduo 增加选项看起来不起作用，因为ssr-local并不支持这个混淆。我认为把tls1.2_ticket_fastauth混淆自动转换成tls1.2_ticket_auth可能更好。

**Comment by paradiseduo** [comment]
> @paradiseduo 增加选项看起来不起作用，因为ssr-local并不支持这个混淆。我认为把tls1.2_ticket_fastauth混淆自动转换成tls1.2_ticket_auth可能更好。

我自己搭建了服务器测试过，是可以使用的啊，不过还是按照你的建议改一下吧，毕竟ssr-local不好维护了

**Comment by redapple0204** [comment]
@paradiseduo 好的，谢谢！
