### ISSUE TITLE
状态栏的图标运行一段时间后会自动消失

### ISSUE THREAD

**Issue by shibor** [wzdnzd/ShadowsocksX-NG-R#18]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.15.3 (19D76)
- Shadowsocksx-NG-R8 1.4.7

**Comment by anhjisjlyq** [comment]
遇到相同的问题

* macOS 10.13.2
* Shadowsocksx-NG 1.4.7

**Comment by Jefferlau** [comment]
相似的问题发生在手动更新订阅：
- macOS 10.15.3
- ShadowsocksX-NG-R 1.4.8

**Comment by wzdnzd** [comment]
目前没遇到这种情况， @shibor  @anhjisjlyq 请尝试更新到最新版试试

**Comment by fbion** [comment]
> 目前没遇到这种情况， @shibor @anhjisjlyq 请尝试更新到最新版试试

进程蹦溃了
系统有crash日志

**Comment by fbion** [comment]
@shibor @anhjisjlyq   @wzdnzd 
~/Library/Logs/DiagnosticReports/
目录中的
ShadowsocksX-NG.*.crash发出来
