### ISSUE TITLE
选中的节点在更新订阅之后位置将会被提到第一位

### ISSUE THREAD

**Issue by redapple0204** [wzdnzd/ShadowsocksX-NG-R#20]
### 复现步骤：
1.使用订阅功能，并且先更新订阅一次以确保有服务器可以选择
2.选择位于订阅组的某个服务器 ~~修改一些无关紧要的配置（例如修改混淆参数，或者如果原来是http-simple混淆就换成http-post，反之亦然）；如果订阅组内所有服务器均使用tls1.2_ticket_fastauth混淆则不需要修改配置~~ 只需要选择服务器即可，看起来这是一个普遍发生的问题。
3.更新订阅

### 出现的情况：
选中的那个更改配置后的服务器将会被提到所在组的第一位（初步猜测是因为在更新订阅之前会清除所在组的所有服务器导致的）

### 期待的情况：
选中的服务器位置仍然在原来的位置

谢谢！

**Comment by paradiseduo** [comment]
清空服务器和保留当前选中服务器目前看来属于必要的操作。
原因如下：
1.如果当前选中的服务器已经不在订阅内，那么按照你的要求，这里就无法选择。
2.判断订阅服务器是否相同目前仅根据名称判断，并不是根据配置是否相同去判断，因此要做到每次仅更新改变的配置会非常繁琐，而且多余的计算也会影响订阅更新的速度

所以目前来看，当前的模式属于较好的选择
