### ISSUE TITLE
lncn.org 一键导入所有ssr 失败

### ISSUE THREAD

**Issue by TomYule** [wzdnzd/ShadowsocksX-NG-R#21]
**System and Shadowsocksx-NG-R8 version:**
新版本为 1.4.8 build 2
- macOS 10.12.4 beta (16E144f)
- Shadowsocksx-NG-R8 1.3.9-build4

**Expected behavior:**
ssr://NDUuMTQ0LjIuNTE6NTU5ODpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ05YSncvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJRUSZncm91cD1URzVqYmk1dmNtYw,ssr://NDUuMTQ3LjIwMS4xNjg6NTU5ODpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ05YSncvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJRZyZncm91cD1URzVqYmk1dmNtYw,ssr://ODUuMTE3LjIzNC45ODo1NTk4Om9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTlhKdy8_b2Jmc3BhcmFtPSZyZW1hcmtzPTZJNnI1cGF2NTZlUlF3Jmdyb3VwPVRHNWpiaTV2Y21j,ssr://NDUuMTQ0LjIuMTg2OjU1OTg6b3JpZ2luOnJjNDpwbGFpbjpiRzVqYmk1dmNtY2dOWEp3Lz9vYmZzcGFyYW09JnJlbWFya3M9Nkk2cjVwYXY1NmVSUkEmZ3JvdXA9VEc1amJpNXZjbWM,ssr://NDUuMTQ3LjIwMC4yMzc6NTU5ODpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ04zUmsvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJTUSZncm91cD1URzVqYmk1dmNtYw,ssr://NDYuMTcuNDUuMTk0OjU1OTg6b3JpZ2luOnJjNDpwbGFpbjpiRzVqYmk1dmNtY2dOM1JrLz9vYmZzcGFyYW09JnJlbWFya3M9Nkk2cjVwYXY1NmVSU2cmZ3JvdXA9VEc1amJpNXZjbWM,ssr://MTkzLjM4LjUwLjIwNjo1NTk4Om9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTjNSay8_b2Jmc3BhcmFtPSZyZW1hcmtzPTZJNnI1cGF2NTZlUlN3Jmdyb3VwPVRHNWpiaTV2Y21j,ssr://NDUuMTM2LjI0NC4yMDQ6NTU5ODpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ04zUmsvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJUQSZncm91cD1URzVqYmk1dmNtYw,ssr://MTAzLjEyNC4xMDYuMTgyOjU1OTg6b3JpZ2luOnJjNDpwbGFpbjpiRzVqYmk1dmNtY2dPR3RsLz9vYmZzcGFyYW09JnJlbWFya3M9NXJTYjVwMko1NS0yUVEmZ3JvdXA9VEc1amJpNXZjbWM,ssr://MTAzLjEyNC4xMDcuMTM2OjU1OTg6b3JpZ2luOnJjNDpwbGFpbjpiRzVqYmk1dmNtY2dPR3RsLz9vYmZzcGFyYW09JnJlbWFya3M9NXJTYjVwMko1NS0yUWcmZ3JvdXA9VEc1amJpNXZjbWM,ssr://NDUuODkuMTk3LjEyMDo1NTk4Om9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnT0d0bC8_b2Jmc3BhcmFtPSZyZW1hcmtzPTVyU2I1cDJKNTUtMlF3Jmdyb3VwPVRHNWpiaTV2Y21j,ssr://MTAzLjEyNC4xMDcuMjA0OjU1OTg6b3JpZ2luOnJjNDpwbGFpbjpiRzVqYmk1dmNtY2dPR3RsLz9vYmZzcGFyYW09JnJlbWFya3M9NXJTYjVwMko1NS0yUkEmZ3JvdXA9VEc1amJpNXZjbWM

![图片](https://user-images.githubusercontent.com/13266764/75940018-db0fc200-5ec6-11ea-81b7-2df63bc8a768.png)

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG-R8` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Tips:**

- Always check for the latest update, some known bug has been fix in the latest release such as old version not support auth_aes_md5 auth_aes_sha1

- Beta version of macOS also may couse some problems

- ss-local compiled by macOS Sierra 10.12 not compatite with 10.11, some old release's ss-local are compiled using 10.12 will not work on 10.11, new release are try build in 10.10 to max fit the compatite

**Comment by wzdnzd** [comment]
一行一个账号，不支持逗号分隔

**Comment by TomYule** [comment]
这个 可以优化一下么 我目前用的https://github.com/qinyuhang/ShadowsocksX-NG-R/releases
这个版本 都支持

**Comment by wzdnzd** [comment]
OK了，你可以试试
