### ISSUE TITLE
ShadowsocksX-NG-R 1.4.8 不向下兼容

### ISSUE THREAD

**Issue by TomYule** [wzdnzd/ShadowsocksX-NG-R#23]
**System and Shadowsocksx-NG-R8 version:**
ShadowsocksX-NG-R 1.4.8
- macOS 10.14.5

**Expected behavior:**
![image](https://user-images.githubusercontent.com/13266764/75946575-6776b080-5ed8-11ea-8574-313f665ada92.png)

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG-R8` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Tips:**

- Always check for the latest update, some known bug has been fix in the latest release such as old version not support auth_aes_md5 auth_aes_sha1

- Beta version of macOS also may couse some problems

- ss-local compiled by macOS Sierra 10.12 not compatite with 10.11, some old release's ss-local are compiled using 10.12 will not work on 10.11, new release are try build in 10.10 to max fit the compatite

**Comment by wzdnzd** [comment]
重新打包了一下 你可以重新试试

**Comment by TomYule** [comment]
release 更新了?
