### ISSUE TITLE
希望可以更改测速方式为服务器端ping

### ISSUE THREAD

**Issue by kaiwu-astro** [wzdnzd/ShadowsocksX-NG-R#24]
你好！我发现通过本软件测速经常不能反映服务器的真实连接性，经常出现ping得通但是google还是连不上，导致还要手动测试
最近iOS上的shadowrocket增加了一个测速方式（设置-延迟测试方式-CONNECT）为Test www.gstatic.com via server，改为这个测速方式过后，ping得通的服务器就是真实可用、可以直接选择的服务器
另外安卓上的shadowsocksR软件也是采用的此方法测试延迟（打开代理过后ping www.google.com），也能反映真实连接性
所以能否在此优化一下？每天在电脑上要花很长时间测试真实可用的服务器，真的很费劲。谢谢！

**Comment by paradiseduo** [comment]
之前考虑过这个方案，但是难点在于需要先应用每一个节点，然后再去ping，如果一旦其中有几个不通，那么测速的时间将会很长。另外也有可能会导致计算机代理异常。
如果想要批量测速，建议看一下这两个项目
https://github.com/NyanChanMeow/SSRSpeed
https://github.com/mobier/shadowsocksr-speed

**Comment by kaiwu-astro** [comment]
感谢回复！
是的，shadowrocket在切换为这种测速模式过后，在有不通的情况下确实比较慢，但是如果是一般的tcping过后确实还得一个一个测试（也可能是我的订阅源比较垃圾orz），这种即使是慢，那也比手动去浏览器google来测试要快太多了
感谢，这两个项目应该能暂时解决我的这个需求，不过依然建议您考虑这个功能，谢谢。

**Comment by wzdnzd** [comment]
正如@paradiseduo 所说，如果要实现该功能，只能挨个把节点作为代理节点测试一遍，然后通过curl -socks5这样的命令去测试，这个过程很耗时，而且得不断重启ss-local，所以可能会导致一些潜在的问题，目前暂时不考虑
