### ISSUE TITLE
每次更新订阅或者服务器测速后选择的节点会自动变成第一个

### ISSUE THREAD

**Issue by appdev** [wzdnzd/ShadowsocksX-NG-R#26]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.15.3 (19D76)
- Shadowsocksx-NG-R8 1.4.8(5)

每次更新订阅后，会自动选择节点列表中的第一个
每次服务器测速后，会自动选择测速最快的那个节点。（然而我最快的是本地的一个节点）

是故意这么设计的，还是bug呢

**Comment by wzdnzd** [comment]
+ 每次更新订阅后，会自动选择节点列表中的第一个
> 更新订阅的时候，会清除旧的节点，所以订阅成功后会选中第一个节点

+ 每次服务器测速后，会自动选择测速最快的那个节点，但最快的是本地的一个节点
> 如果这个节点没有存在的必要的话，可以配合订阅的【过滤】功能使用，目前是按照备注信息过滤，支持正则表达式
![image](https://user-images.githubusercontent.com/8565764/76614520-3e4ec380-655b-11ea-865f-582c294a176f.png)


+ 为什么能明显看到选中节点的变化
> 因为目前是等订阅更新完以后才开始测速，选出延时最小的节点
