### ISSUE TITLE
服务器地址是否有误

### ISSUE THREAD

**Issue by FeiLyu** [wzdnzd/ShadowsocksX-NG-R#28]
EXT-HK 页面上显示的服务器地址是：ss://cmM0LW1kNToxSUFiaEQ2Nl。。。。这种无法添加，是否有误？

**Comment by paradiseduo** [comment]
ss://… 及 ssr://… 这样的链接都是经过 url_safe  Base64 编码生成的，就是先通过标准的 Base64 编码，然后再把编码内容中的 + 和 / 分别替换为 – 和 _ 这两个字符。你这个链接可以手动Base64解码试一下，如果解不出来就是错误的格式。
