### ISSUE TITLE
无法打开网站

### ISSUE THREAD

**Issue by horaynia** [wzdnzd/ShadowsocksX-NG-R#29]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.12.4 beta (16E144f)
- Shadowsocksx-NG-R8 1.3.9-build4

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG-R8` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Tips:**

- Always check for the latest update, some known bug has been fix in the latest release such as old version not support auth_aes_md5 auth_aes_sha1

- Beta version of macOS also may couse some problems

- ss-local compiled by macOS Sierra 10.12 not compatite with 10.11, some old release's ss-local are compiled using 10.12 will not work on 10.11, new release are try build in 10.10 to max fit the compatite

1.4.8安装并导入sr链接后，点击自动模式。然后无法上网（Google，YouTube）等。是咋回事儿

**Comment by horaynia** [comment]
是还需要怎么设置吗？之前用的是1.4.4-R8的。换回又好了。请大神告知。

**Comment by wzdnzd** [comment]
+ 如果是浏览器装了switchyomega插件的话，请确认插件配置的端口和该软件的端口一致
+ 确认代理节点是否真的可用
+ 确认ss-local是否正常运行，可以在终端执行 lsof -i:`端口号`看看有没有进程，socks5端口默认`1087`，可执行`lsof -i:1087`试试

**Comment by horaynia** [comment]
- 浏览器没有安装过switchyomega插件

- 节点真实可用。节点是在魅影购买，未到期。我用1.4.4-r8就可以使用

- 因为安装1.4.4-r8，其socks5端口默认为1086，卸载掉安装此版本（1.4.8）其默认端口仍为1086，
在端口为1086下，执行 lsof -i:1086无任何反应；执行lsof -i:1087，出现“COMMAND PID        USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
v2ray   626 zhachaoteng    8u  IPv4 0x67a4094cc1501a75      0t0  TCP localhost:cplscrambler-in (LISTEN)”这些英文。在修改端口为1087时，执行lsof -i:1087，出现“COMMAND PID        USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
v2ray   626 zhachaoteng    8u  IPv4 0x67a4094cc1501a75      0t0  TCP localhost:cplscrambler-in (LISTEN)”

- 请问这是什么意思。无论是默认端口1086，还是修改为1087都无法上网。

**Comment by horaynia** [comment]
> 在 2020年3月15日，上午10:34，wzdnzd <notifications@github.com> 写道：
> 
> 
> 如果是浏览器装了switchyomega插件的话，请确认插件配置的端口和该软件的端口一致
> 确认代理节点是否真的可用
> 确认ss-local是否正常运行，可以在终端执行 lsof -i:端口号看看有没有进程，socks5端口默认1087，可执行lsof -i:1087试试
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwzdnzd%2FShadowsocksX-NG-R%2Fissues%2F29%23issuecomment-599159662&data=02%7C01%7C%7C51e4d24165164ab0d29808d7c88969fa%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637198364839510800&sdata=bILpzFlhIMb6Oukt%2FQ5tClKKJ9a%2FFKvb3DL%2BXJCUKCc%3D&reserved=0>, or unsubscribe <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMBSJGZ4N3OUX6I65SUDH3DRHQ5EBANCNFSM4LIWF5KA&data=02%7C01%7C%7C51e4d24165164ab0d29808d7c88969fa%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637198364839520794&sdata=stm4IrOZ8mCLIJ6qVqTocPsTRPI5E%2FVd%2F8Ngt8u6XE4%3D&reserved=0>.
> 

浏览器没有安装过switchyomega插件

节点真实可用。节点是在魅影购买，未到期。我用1.4.4-r8就可以使用

因为安装1.4.4-r8，其socks5端口默认为1086，卸载掉安装此版本（1.4.8）其默认端口仍为1086，
在端口为1086下，执行 lsof -i:1086无任何反应；执行lsof -i:1087，出现“COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME
v2ray 626 zhachaoteng 8u IPv4 0x67a4094cc1501a75 0t0 TCP localhost:cplscrambler-in (LISTEN)”这些英文。在修改端口为1087时，执行lsof -i:1087，出现“COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME
v2ray 626 zhachaoteng 8u IPv4 0x67a4094cc1501a75 0t0 TCP localhost:cplscrambler-in (LISTEN)”

请问这是什么意思。无论是默认端口1086，还是修改为1087都无法上网。

**Comment by horaynia** [comment]
<img width="516" alt="iShot2020-03-15下午02 52 47" src="https://user-images.githubusercontent.com/50537627/76697010-a83aaa80-66cc-11ea-8fee-e45a70e4a03d.png">
<img width="606" alt="iShot2020-03-15下午02 53 20" src="https://user-images.githubusercontent.com/50537627/76697019-c0122e80-66cc-11ea-9349-84e6fd4d4f82.png">

**Comment by horaynia** [comment]
我将端口修改为1087，执行情况和端口为1086的执行情况是一样的。如上图。不知道是哪儿出了问题

**Comment by wzdnzd** [comment]
你试试`ps -ef | grep ss-local`看看ss-local是否有正常启动 例外 有日志吗  你似乎也开着v2ray 不知道是否有影响

**Comment by horaynia** [comment]
> 在 2020年3月15日，下午3:43，wzdnzd <notifications@github.com> 写道：
> 
> 
> 你试试ps -ef | grep ss-local看看ss-local是否有正常启动 例外 有日志吗 你似乎也开着v2ray 不知道是否有影响
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub <https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwzdnzd%2FShadowsocksX-NG-R%2Fissues%2F29%23issuecomment-599178558&data=02%7C01%7C%7Cc6070f6bd1a445b456bd08d7c8b49293%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637198550181321994&sdata=KGbvD%2FwjZLZ1tdigLluyHgfO%2B47z1s77iE63b4co%2Brk%3D&reserved=0>, or unsubscribe <https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMBSJG4QZGRQNAJNFNAGHALRHSBKRANCNFSM4LIWF5KA&data=02%7C01%7C%7Cc6070f6bd1a445b456bd08d7c8b49293%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637198550181321994&sdata=AC1IVlv1Xi0rt%2F6wTxfOGadwArBNhBrgYaN%2BIzByF64%3D&reserved=0>.
> 
日志怎么提取。我之前是安装了v2ray，但是后面我卸载了，还是无法上网。
这是正常启动了吗？

**Comment by horaynia** [comment]
> 在 2020年3月15日，下午4:22，查超腾 <alvin.zha@hotmail.com> 写道：
> 
> 
> 
>> 在 2020年3月15日，下午3:43，wzdnzd <notifications@github.com <mailto:notifications@github.com>> 写道：
>> 
>> 
>> 你试试ps -ef | grep ss-local看看ss-local是否有正常启动 例外 有日志吗 你似乎也开着v2ray 不知道是否有影响
>> 
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub <https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwzdnzd%2FShadowsocksX-NG-R%2Fissues%2F29%23issuecomment-599178558&data=02%7C01%7C%7Cc6070f6bd1a445b456bd08d7c8b49293%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637198550181321994&sdata=KGbvD%2FwjZLZ1tdigLluyHgfO%2B47z1s77iE63b4co%2Brk%3D&reserved=0>, or unsubscribe <https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMBSJG4QZGRQNAJNFNAGHALRHSBKRANCNFSM4LIWF5KA&data=02%7C01%7C%7Cc6070f6bd1a445b456bd08d7c8b49293%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637198550181321994&sdata=AC1IVlv1Xi0rt%2F6wTxfOGadwArBNhBrgYaN%2BIzByF64%3D&reserved=0>.
>> 
> 日志怎么提取。我之前是安装了v2ray，但是后面我卸载了，还是无法上网。
> 这是正常启动了吗？
> <iShot2020-03-15下午04.21.31.png>
这是软件里的日志。你看下是这个吗？

**Comment by horaynia** [comment]
麻烦大神给看下，难道就我一个出现这样的问题。------------------ 原始邮件 ------------------发件人: wzdnzd  <notifications@github.com>发送时间: 2020年3月15日 15:43收件人: wzdnzd/ShadowsocksX-NG-R <ShadowsocksX-NG-R@noreply.github.com>抄送: horaynia <Alvin.zha@hotmail.com>, Comment <comment@noreply.github.com>主题: 回复：[wzdnzd/ShadowsocksX-NG-R] 无法打开网站 (#29)
你试试ps -ef | grep ss-local看看ss-local是否有正常启动 例外 有日志吗  你似乎也开着v2ray 不知道是否有影响

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/wzdnzd/ShadowsocksX-NG-R/issues/29#issuecomment-599178558",
"url": "https://github.com/wzdnzd/ShadowsocksX-NG-R/issues/29#issuecomment-599178558",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
