### ISSUE TITLE
Random crashes on macOS 10.14.6

### ISSUE THREAD

**Issue by bailsafe** [wzdnzd/ShadowsocksX-NG-R#30]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.14.6 (18G103)
- Shadowsocksx-NG-R8 1.4.8 (1)

**Expected behavior:**

To not crash?

**Actual behavior:**

App crashes randomly throughout the day.

**Steps to reproduce:**

Normal usage.

**How often does this happen?**

Every few hours.

**ss-local.log**

(not found, verbose mode is on)

**Application log**

```
An uncaught exception was raised
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Couldn't posix_spawn: error 35'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff3b83fa7d __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff65f36a17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3b83f8af +[NSException raise:format:] + 201
	3   Foundation                          0x00007fff3da33f79 -[NSConcreteTask launchWithDictionary:error:] + 4437
	4   ShadowsocksX-NG                     0x0000000107bf32ca ShadowsocksX-NG + 58058
	5   ShadowsocksX-NG                     0x0000000107bf3558 ShadowsocksX-NG + 58712
	6   Foundation                          0x00007fff3da367fb __NSFireTimer + 80
	7   CoreFoundation                      0x00007fff3b7a87c0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	8   CoreFoundation                      0x00007fff3b7a836c __CFRunLoopDoTimer + 851
	9   CoreFoundation      <…>
-[PersistentAppsSupport applicationQuit:] | for app:ShadowsocksX-NG, _appTrackingState = 2
SecTranslocate: problem deleting translocation after app death: /private/var/folders/mm/wxw4d2p56js01kqxfpysnmk40000gn/T/AppTranslocation/A41D725A-354E-46DF-A35E-EE352AA6B8C9/d/ShadowsocksX-NG-R.app
```

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Tips:**

- Always check for the latest update, some known bug has been fix in the latest release such as old version not support auth_aes_md5 auth_aes_sha1

- Beta version of macOS also may couse some problems

- ss-local compiled by macOS Sierra 10.12 not compatite with 10.11, some old release's ss-local are compiled using 10.12 will not work on 10.11, new release are try build in 10.10 to max fit the compatite

**Comment by fbion** [comment]
ls ~/Library/Logs/DiagnosticReports/ShadowsocksX-NG_*.crash

**Comment by bailsafe** [comment]
> ls ~/Library/Logs/DiagnosticReports/ShadowsocksX-NG_*.crash

Also not found here. Console says it is saved but I cannot find the crash logs at all.

**Comment by wzdnzd** [comment]
@bailsafe Maybe you can update it and try again. Please feel free to let me know if there is any issues.

**Comment by bailsafe** [comment]
Upgraded to latest version, still crashes often. Still no logs found in ~/Library/Logs/DiagnosticReports even though verbose mode is turned on.

**Comment by wzdnzd** [comment]
Sorry, the problem is difficult to locate without a log file, and I cannot reproduce the problem.
