### ISSUE TITLE
求助大神，飞不了

### ISSUE THREAD

**Issue by norangit** [wzdnzd/ShadowsocksX-NG-R#31]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.14.5
- Shadowsocksx-NG 1.4.8 (7)

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**
昨天还可以飞，今天就不行了，但是什么也没动，同样的服务器配置，在苹果手机和 ipad 上是可以的
(N/A for feature requests)

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG-R8` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)
之前没细看日志的信息，刚才好好看了看，端口改了也还是不行

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**
下面的文件需要把.txt 后缀去掉
[ShadowsocksX-NG_2020-03-15-193121_LMBP.crash.txt](https://github.com/wzdnzd/ShadowsocksX-NG-R/files/4334123/ShadowsocksX-NG_2020-03-15-193121_LMBP.crash.txt)

If the app crashes and pop up a crash log, please copy and paste here

**Tips:**

- Always check for the latest update, some known bug has been fix in the latest release such as old version not support auth_aes_md5 auth_aes_sha1

- Beta version of macOS also may couse some problems

- ss-local compiled by macOS Sierra 10.12 not compatite with 10.11, some old release's ss-local are compiled using 10.12 will not work on 10.11, new release are try build in 10.10 to max fit the compatite

**Comment by norangit** [comment]
@paradiseduo pls help help, thx very very much.

**Comment by paradiseduo** [comment]
首先看一下你电脑上是不是还安装了别的代理软件，比如V2ray和ss，如果有，那么你需要改一下他们的本地端口，然后再开SSR试试。
如果没安装其他代理软件，那么先关闭SSR软件，打开终端，依次输入：
cd $HOME/Library/Application\ Support/
open .

上面两条命令可以打开Application Suppor文件夹，找到ShadowsocksX-NG和ShadowsocksX-NG-R8的文件夹，直接删除，然后重新打开SSR。

另外日志中会包含服务器等敏感信息，所以尽量脱敏后贴出来。。建议你修改一下上面贴的日志。。

**Comment by norangit** [comment]
首先，非常感谢您的及时答复，我把我的 sslocal 日志删了。
是的老早前我装的是 1.4.4 的一个版本，后来删了那个装了一次你 repo 里的，然后不好使，又装了现在这个 repo 里的，昨天还可以，今天就不行了，但是手机和 pad 正常。

于是我在命令行用 find 命令把能搜到的 Shadowsocks*的都删了，然后重新下载的当前这个 repo 里的，打开后还是不行。后来我查看ss-local 日志发现端口被占用所以我才改成了 10870 的，我在飞机里把本地 socks5 监听端口改成了 10870，然后我在 termial 里 lsof发现 1087 的进程是

```privoxy 38001 XX    3u  IPv4 0x95127318d756a93b      0t0  TCP localhost:cplscrambler-in (LISTEN)```

10870的进程是
```ss-local 37996 XX    8u  IPv4 0x95127318bccb363b      0t0  TCP localhost:10870 (LISTEN)```

如果我把飞机退了，这个 1087 对应的进程也退出了，不知道是为什么，大神？

update:

我关了软件，重新把端口改回去 1087，查看 ss-local 日志也成功了， lsof 的信息如下：
```
ss-local 38320 XX    8u  IPv4 0x95127318b6f7393b      0t0  TCP localhost:cplscrambler-in (LISTEN)
```

ss-local.log如下：

```
2020-03-15 22:27:42 INFO: initializing ciphers... salsa20
 2020-03-15 22:27:42 INFO: listening at 127.0.0.1:1087
```

**Comment by mayochow** [comment]
你也是1.48-5升级到1.48-7吗？

**Comment by norangit** [comment]
@paradiseduo 大神，如何把所有 ss 的东西都删除干净呢？我今天只是 find / Shadowsock* 能找到的都删了，我现在想都删了，然后下一个上个版本的试试，不知道还往哪儿写配置文件之类的没有了。
不然的话，昨天我还好好的，今天就不行了，然后我就看到本 repo 的作者有更新，就下了个试试，还是不行，头疼😌

**Comment by wzdnzd** [comment]
@norangit
```shell
cd ~/Library/Application\ Support/ShadowsocksX-NG-R8  
```
使用 `rm -rf 文件名`删除除了privoxy、privoxy-3.0.26.static、privoxy.config、ss-local-config.json以外的所有文件，然后重新运行试试

**Comment by norangit** [comment]
@wzdnzd 好的，大神，我试试

**Comment by norangit** [comment]
@wzdnzd 还是不行，@paradiseduo 说的是直接把文件夹干掉了，我今天把 Shadowsocks* 都删了一次，这个 ~/Library/Application\ Support/ShadowsocksX-NG-R8 文件夹刚才也彻底删了一次，应用程序里的 ShadowsocksX-NG-R8 也删了，重新解压，拉进来还是一样的，打开后我的订阅就在呢，看起来哪儿还是有缓存的吧。。。DD 疼啊😿

**Comment by norangit** [comment]
我查看了下日志，在系统日志里貌似有个异常，不知道是不是有影响：
```
默认	23:20:36.550088 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG-R8/proxy_conf_helper
默认	23:20:36.614943 +0800	ShadowsocksX-NG	pac proxy set to off
默认	23:20:36.616225 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG-R8/proxy_conf_helper
默认	23:20:36.725049 +0800	ShadowsocksX-NG	pac proxy set to auto
默认	23:20:38.736710 +0800	ShadowsocksX-NG	LSExceptions shared instance invalidated for timeout.
默认	23:20:46.169672 +0800	ShadowsocksX-NG	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 0 vs 17732, 513, <private>

```

ss-local 日志是正常的：

```
2020-03-15 23:20:31 INFO: method salsa20
 2020-03-15 23:20:31 INFO: obfs tls1.2_ticket_auth
 2020-03-15 23:20:31 INFO: obfs_param 
 2020-03-15 23:20:31 INFO: using tcp fast open
 2020-03-15 23:20:31 INFO: initializing ciphers... salsa20
 2020-03-15 23:20:31 INFO: tcp port reuse enabled
 2020-03-15 23:20:31 INFO: listening at 127.0.0.1:1087
 2020-03-15 23:20:36 INFO: protocol auth_chain_b
 2020-03-15 23:20:36 INFO: protocol_param 
 2020-03-15 23:20:36 INFO: method salsa20
 2020-03-15 23:20:36 INFO: obfs tls1.2_ticket_auth
 2020-03-15 23:20:36 INFO: obfs_param 
 2020-03-15 23:20:36 INFO: using tcp fast open
 2020-03-15 23:20:36 INFO: initializing ciphers... salsa20
 2020-03-15 23:20:36 INFO: tcp port reuse enabled
 2020-03-15 23:20:36 INFO: listening at 127.0.0.1:1087
```

**Comment by Jacob-pixil** [comment]
同样的问题，新版本用不了。 你解决了吗？

**Comment by norangit** [comment]
@wzdnzd 卧槽，好了，非起来了。不知道为什么，我刚才只是把

```
~/Library/Application\ Support/ShadowsocksX-NG-R8 
```
这个文件夹删了，应用程序里的 ShadowsocksX-NG-R 也删了，然后重新解压，拉进应用程序里

以上动作，重复执行了 2 次。。。，然后刚才打开后又试着确认了下，非起来了。。。不知道为什么

anyway, 这么晚了，非常 非常感谢你的回复 @wzdnzd 

还有个 crash 的日志，我在上面也放了，这个 crash 的问题存在好久了，我刚刚装成 @paradiseduo  repo 里的 1.4.9 了，用段时间看看会不会再 crash。。。
