### ISSUE TITLE
新升级最新的Shadowsocksx-NG-R8-1.48-7版本后有严重问题

### ISSUE THREAD

**Issue by mayochow** [wzdnzd/ShadowsocksX-NG-R#32]
大神，MAC OS 10.15.3下一直用的是你的Shadowsocksx-NG-R8-1.48-5版本，一直正常使用！今天升级到最新版后不能翻墙，不管是PAC还是全局。卸载后再装回正常版本还是这个问题，求助！谢谢

**Comment by wzdnzd** [comment]
因为升级了底层的`ss-local`，可能会存在一些问题，可先尝试删除旧的目录，重新运行一下试试，在我的两台mbp上是没问题的

```shell
cd ~/Library/Application\ Support/ShadowsocksX-NG-R8  
```
使用 `rm -rf 文件名`删除除了privoxy、privoxy-3.0.26.static、privoxy.config、ss-local-config.json以外的所有文件，然后重新运行试试

**Comment by Jacob-pixil** [comment]
这个命令是在那里输出运行的呀， 我也是出现不能翻的问题， 用老的1.44版本就可以

**Comment by Jacob-pixil** [comment]
我已经把application support里的文件夹全部删掉了，还是不行

**Comment by norangit** [comment]
refer to #31

**Comment by Jacob-pixil** [comment]
> refer to #31

按照方法重复多次的确没成功， 不过换成@paradiseduo的1.4.9的版本的确能用了，可能是ss-local的版本问题？

**Comment by norangit** [comment]
不晓得，可能 @wzdnzd 作者的环境跟我们的不一样吧，所以可能复现不了

**Comment by wzdnzd** [comment]
这个我这边暂时也复现 不了  等后续有时间再研究一下吧   升级后有问题的都可以在这反馈一下😂

> 也可按照以下思路排查一下：
+ 查看文件目录是否正常
```shell
cd ~/Library/Application\ Support/ShadowsocksX-NG-R8
# 可能需要使用brew安装一下tree，使用 ls -al自己挨个对比一下也可以
tree

├── libcares.2.dylib
├── libcares.dylib -> /Users/xxx/Library/Application\ Support/ShadowsocksX-NG-R8/libcares.2.dylib
├── libev.4.dylib
├── libmbedcrypto.2.16.5.dylib
├── libmbedcrypto.2.dylib -> /Users/xxx/Library/Application\ Support/ShadowsocksX-NG-R8/libmbedcrypto.2.16.5.dylib
├── libmbedcrypto.3.dylib -> /Users/xxx/Library/Application\ Support/ShadowsocksX-NG-R8/libmbedcrypto.2.16.5.dylib
├── libpcre.1.dylib
├── libsodium.23.dylib
├── libsodium.dylib -> /Users/xxx/Library/Application\ Support/ShadowsocksX-NG-R8/libsodium.23.dylib
├── privoxy -> /Users/xxx/Library/Application\ Support/ShadowsocksX-NG-R8/privoxy-3.0.26.static/privoxy
├── privoxy-3.0.26.static
│   └── privoxy
├── privoxy.config
├── ss-local -> /Users/xxx/Library/Application\ Support/ShadowsocksX-NG-R8/ss-local-3.3.4/ss-local
├── ss-local-3.3.4
│   └── ss-local
└── ss-local-config.json
```
+ 查看socks5端口是否正常
```shell
# lsof -i:端口号
lsof -i:1086

COMMAND     PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Google     5898  xxx   28u  IPv4 0xdxxx     0t0  TCP localhost:55835->localhost:socks (ESTABLISHED)
ss-local  10991  xxx    6u  IPv4 0xdxxx    0t0  TCP localhost:socks (LISTEN)
ss-local  10991  xxx   11u  IPv4 0xdxxx     0t0  TCP localhost:socks->localhost:55872 (ESTABLISHED)
ss-local  10991  xxx   14u  IPv4 0xdxxx      0t0  TCP localhost:socks->localhost:55852 (ESTABLISHED)
ss-local  10991  xxx   24u  IPv4 0xdxxx      0t0  TCP localhost:socks->localhost:55835 (ESTABLISHED)
privoxy   10996  xxx    5u  IPv4 0xdxxx      0t0  TCP localhost:55852->localhost:socks (ESTABLISHED)
privoxy   10996  xxx    9u  IPv4 0xdxxx      0t0  TCP localhost:55872->localhost:socks (ESTABLISHED)
```
+ 检查ss-local是否正常工作
```shell
ps -ef | grep ss-local
```
+ 手动运行ss-local试试
```shell
launchctl load -wF "$HOME/Library/LaunchAgents/com.qiuyuzhou.shadowsocksX-NG.local.plist"
launchctl start com.qiuyuzhou.shadowsocksX-NG.local
```
+ 再不济，通过brew安装ss-local依赖库，然后手动启动试试
```shell
brew brew install shadowsocks-libev
./ss-local -c ss-local-config.json
```

**Comment by paradiseduo** [comment]
> ```shell
> ss-local
> ```

你升级的是这个项目里的ss-local吗？
https://github.com/shadowsocks/shadowsocks-libev

这个是项目只支持SS，不支持SSR，，我之前升级试过，加了SSR的协议和混淆数据会解密失败。

目前我找到最新的支持SSR的ss-local是：
https://github.com/shadowsocksrr/shadowsocksr-libev
我也尝试升级过，但是效果不好。

目前我想到的方案是使用Python版本的SSR，然后使用pyinstaller打包成二进制文件，然后更新，但是那样一是需要导入很多附属文件，二是需要改动不少代码来调用，工作量较大。

**Comment by horaynia** [comment]
我的也是，安装1.4.8完全无法爬墙。安装会原版的1.4.4恢复正常。不知道咋回事儿

**Comment by horaynia** [comment]
> > refer to #31
> 
> 按照方法重复多次的确没成功， 不过换成@paradiseduo的1.4.9的版本的确能用了，可能是ss-local的版本问题？
paradiseduo大神的1.4.9没有下载地址啊？可以麻烦给个安装包吗？

**Comment by horaynia** [comment]
> ```shell
> ```shell
> ss-local
> ```
> 
> 
> 
> 你升级的是这个项目里的ss-local吗？
> https://github.com/shadowsocks/shadowsocks-libev
> 这个是项目只支持SS，不支持SSR，，我之前升级试过，加了SSR的协议和混淆数据会解密失败。
> 目前我找到最新的支持SSR的ss-local是：
> https://github.com/shadowsocksrr/shadowsocksr-libev
> 我也尝试升级过，但是效果不好。
> 目前我想到的方案是使用Python版本的SSR，然后使用pyinstaller打包成二进制文件，然后更新，但是那样一是需要导入很多附属文件，二是需要改动不少代码来调用，工作量较大。
> ```

大神，您的1.4.9的是没有安装包的吗？是需要别的方式安装吗？小白一个。可以打包个安装包吗？感谢

**Comment by paradiseduo** [comment]
> > ```shell
> > ```shell
> > ss-local
> > ```
> > 
> > 
> > 你升级的是这个项目里的ss-local吗？
> > https://github.com/shadowsocks/shadowsocks-libev
> > 这个是项目只支持SS，不支持SSR，，我之前升级试过，加了SSR的协议和混淆数据会解密失败。
> > 目前我找到最新的支持SSR的ss-local是：
> > https://github.com/shadowsocksrr/shadowsocksr-libev
> > 我也尝试升级过，但是效果不好。
> > 目前我想到的方案是使用Python版本的SSR，然后使用pyinstaller打包成二进制文件，然后更新，但是那样一是需要导入很多附属文件，二是需要改动不少代码来调用，工作量较大。
> 
> 大神，您的1.4.9的是没有安装包的吗？是需要别的方式安装吗？小白一个。可以打包个安装包吗？感谢

https://github.com/paradiseduo/ShadowsocksX-NG-R8/releases/download/1.4.9/ShadowsocksX-NG-R.zip

**Comment by horaynia** [comment]
> ```shell
> ```shell
> ```shell
> ss-local
> ```
> 
> 
> 你升级的是这个项目里的ss-local吗？
> https://github.com/shadowsocks/shadowsocks-libev
> 这个是项目只支持SS，不支持SSR，，我之前升级试过，加了SSR的协议和混淆数据会解密失败。
> 目前我找到最新的支持SSR的ss-local是：
> https://github.com/shadowsocksrr/shadowsocksr-libev
> 我也尝试升级过，但是效果不好。
> 目前我想到的方案是使用Python版本的SSR，然后使用pyinstaller打包成二进制文件，然后更新，但是那样一是需要导入很多附属文件，二是需要改动不少代码来调用，工作量较大。
> 
> 大神，您的1.4.9的是没有安装包的吗？是需要别的方式安装吗？小白一个。可以打包个安装包吗？感谢
> 
> https://github.com/paradiseduo/ShadowsocksX-NG-R8/releases/download/1.4.9/ShadowsocksX-NG-R.zip
> ```



> ```shell
> ```shell
> ```shell
> ss-local
> ```
> 
> 
> 你升级的是这个项目里的ss-local吗？
> https://github.com/shadowsocks/shadowsocks-libev
> 这个是项目只支持SS，不支持SSR，，我之前升级试过，加了SSR的协议和混淆数据会解密失败。
> 目前我找到最新的支持SSR的ss-local是：
> https://github.com/shadowsocksrr/shadowsocksr-libev
> 我也尝试升级过，但是效果不好。
> 目前我想到的方案是使用Python版本的SSR，然后使用pyinstaller打包成二进制文件，然后更新，但是那样一是需要导入很多附属文件，二是需要改动不少代码来调用，工作量较大。
> 
> 大神，您的1.4.9的是没有安装包的吗？是需要别的方式安装吗？小白一个。可以打包个安装包吗？感谢
> 
> https://github.com/paradiseduo/ShadowsocksX-NG-R8/releases/download/1.4.9/ShadowsocksX-NG-R.zip
> ```

安装完您的和wzdnzd大神的都出现了1个同样的问题，都无法爬墙。安装1.4.4就可以。难道是我的电脑有毒吗？😂。大神可以教教怎么解决吗？

**Comment by paradiseduo** [comment]
> > ```shell
> > ```shell
> > ```shell
> > ss-local
> > ```
> > 
> > 
> > 你升级的是这个项目里的ss-local吗？
> > https://github.com/shadowsocks/shadowsocks-libev
> > 这个是项目只支持SS，不支持SSR，，我之前升级试过，加了SSR的协议和混淆数据会解密失败。
> > 目前我找到最新的支持SSR的ss-local是：
> > https://github.com/shadowsocksrr/shadowsocksr-libev
> > 我也尝试升级过，但是效果不好。
> > 目前我想到的方案是使用Python版本的SSR，然后使用pyinstaller打包成二进制文件，然后更新，但是那样一是需要导入很多附属文件，二是需要改动不少代码来调用，工作量较大。
> > 大神，您的1.4.9的是没有安装包的吗？是需要别的方式安装吗？小白一个。可以打包个安装包吗？感谢
> > https://github.com/paradiseduo/ShadowsocksX-NG-R8/releases/download/1.4.9/ShadowsocksX-NG-R.zip
> 
> > ```shell
> > ```shell
> > ```shell
> > ss-local
> > ```
> > 
> > 
> > 你升级的是这个项目里的ss-local吗？
> > https://github.com/shadowsocks/shadowsocks-libev
> > 这个是项目只支持SS，不支持SSR，，我之前升级试过，加了SSR的协议和混淆数据会解密失败。
> > 目前我找到最新的支持SSR的ss-local是：
> > https://github.com/shadowsocksrr/shadowsocksr-libev
> > 我也尝试升级过，但是效果不好。
> > 目前我想到的方案是使用Python版本的SSR，然后使用pyinstaller打包成二进制文件，然后更新，但是那样一是需要导入很多附属文件，二是需要改动不少代码来调用，工作量较大。
> > 大神，您的1.4.9的是没有安装包的吗？是需要别的方式安装吗？小白一个。可以打包个安装包吗？感谢
> > https://github.com/paradiseduo/ShadowsocksX-NG-R8/releases/download/1.4.9/ShadowsocksX-NG-R.zip
> 
> 安装完您的和wzdnzd大神的都出现了1个同样的问题，都无法爬墙。安装1.4.4就可以。难道是我的电脑有毒吗？😂。大神可以教教怎么解决吗？

先关闭代理
进入~/Library/Application\ Support/ 目录下，删除ShadowsocksX-NG-R8和ShadowsocksX-NG文件夹
然后再进入/Library/Application\ Support/目录下，删除ShadowsocksX-NG-R8和ShadowsocksX-NG文件夹

再重新启动代理。
服务器配置没问题的话，有很大可能是因为代理冲突了。ss-local进程有多个，抢占相同端口。

**Comment by wzdnzd** [comment]
@paradiseduo 是的，就是用的[https://github.com/shadowsocks/shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev)，可能真的是这个原因。缺少测试，失策失策，非常感谢

**Comment by horaynia** [comment]
> ```shell
> ```shell
> ```shell
> ```shell
> ss-local
> ```
> 
> 
> 你升级的是这个项目里的ss-local吗？
> https://github.com/shadowsocks/shadowsocks-libev
> 这个是项目只支持SS，不支持SSR，，我之前升级试过，加了SSR的协议和混淆数据会解密失败。
> 目前我找到最新的支持SSR的ss-local是：
> https://github.com/shadowsocksrr/shadowsocksr-libev
> 我也尝试升级过，但是效果不好。
> 目前我想到的方案是使用Python版本的SSR，然后使用pyinstaller打包成二进制文件，然后更新，但是那样一是需要导入很多附属文件，二是需要改动不少代码来调用，工作量较大。
> 大神，您的1.4.9的是没有安装包的吗？是需要别的方式安装吗？小白一个。可以打包个安装包吗？感谢
> https://github.com/paradiseduo/ShadowsocksX-NG-R8/releases/download/1.4.9/ShadowsocksX-NG-R.zip
> 
> 
> ```shell
> ```shell
> ```shell
> ss-local
> ```
> 
> 
> 你升级的是这个项目里的ss-local吗？
> https://github.com/shadowsocks/shadowsocks-libev
> 这个是项目只支持SS，不支持SSR，，我之前升级试过，加了SSR的协议和混淆数据会解密失败。
> 目前我找到最新的支持SSR的ss-local是：
> https://github.com/shadowsocksrr/shadowsocksr-libev
> 我也尝试升级过，但是效果不好。
> 目前我想到的方案是使用Python版本的SSR，然后使用pyinstaller打包成二进制文件，然后更新，但是那样一是需要导入很多附属文件，二是需要改动不少代码来调用，工作量较大。
> 大神，您的1.4.9的是没有安装包的吗？是需要别的方式安装吗？小白一个。可以打包个安装包吗？感谢
> https://github.com/paradiseduo/ShadowsocksX-NG-R8/releases/download/1.4.9/ShadowsocksX-NG-R.zip
> 
> 安装完您的和wzdnzd大神的都出现了1个同样的问题，都无法爬墙。安装1.4.4就可以。难道是我的电脑有毒吗？😂。大神可以教教怎么解决吗？
> 
> 先关闭代理
> 进入~/Library/Application\ Support/ 目录下，删除ShadowsocksX-NG-R8和ShadowsocksX-NG文件夹
> 然后再进入/Library/Application\ Support/目录下，删除ShadowsocksX-NG-R8和ShadowsocksX-NG文件夹
> 再重新启动代理。
> 服务器配置没问题的话，有很大可能是因为代理冲突了。ss-local进程有多个，抢占相同端口。
> ```
是这两个文件夹吗？但是里面没有ng 的文件夹，只有r8的文件夹。
<img width="806" alt="iShot2020-03-16下午12 10 25" src="https://user-images.githubusercontent.com/50537627/76722755-e1802280-677f-11ea-9d03-e9b7ac2659e8.png">
<img width="806" alt="iShot2020-03-16下午12 10 15" src="https://user-images.githubusercontent.com/50537627/76722761-e6dd6d00-677f-11ea-8287-c1ad983a401e.png">

**Comment by paradiseduo** [comment]
> > ```shell
> > ```shell
> > ```shell
> > ```shell
> > ss-local
> > ```
> > 
> > 
> > 你升级的是这个项目里的ss-local吗？
> > https://github.com/shadowsocks/shadowsocks-libev
> > 这个是项目只支持SS，不支持SSR，，我之前升级试过，加了SSR的协议和混淆数据会解密失败。
> > 目前我找到最新的支持SSR的ss-local是：
> > https://github.com/shadowsocksrr/shadowsocksr-libev
> > 我也尝试升级过，但是效果不好。
> > 目前我想到的方案是使用Python版本的SSR，然后使用pyinstaller打包成二进制文件，然后更新，但是那样一是需要导入很多附属文件，二是需要改动不少代码来调用，工作量较大。
> > 大神，您的1.4.9的是没有安装包的吗？是需要别的方式安装吗？小白一个。可以打包个安装包吗？感谢
> > https://github.com/paradiseduo/ShadowsocksX-NG-R8/releases/download/1.4.9/ShadowsocksX-NG-R.zip
> > ```shell
> > ```shell
> > ```shell
> > ss-local
> > ```
> > 
> > 
> > 你升级的是这个项目里的ss-local吗？
> > https://github.com/shadowsocks/shadowsocks-libev
> > 这个是项目只支持SS，不支持SSR，，我之前升级试过，加了SSR的协议和混淆数据会解密失败。
> > 目前我找到最新的支持SSR的ss-local是：
> > https://github.com/shadowsocksrr/shadowsocksr-libev
> > 我也尝试升级过，但是效果不好。
> > 目前我想到的方案是使用Python版本的SSR，然后使用pyinstaller打包成二进制文件，然后更新，但是那样一是需要导入很多附属文件，二是需要改动不少代码来调用，工作量较大。
> > 大神，您的1.4.9的是没有安装包的吗？是需要别的方式安装吗？小白一个。可以打包个安装包吗？感谢
> > https://github.com/paradiseduo/ShadowsocksX-NG-R8/releases/download/1.4.9/ShadowsocksX-NG-R.zip
> > 安装完您的和wzdnzd大神的都出现了1个同样的问题，都无法爬墙。安装1.4.4就可以。难道是我的电脑有毒吗？😂。大神可以教教怎么解决吗？
> > 先关闭代理
> > 进入~/Library/Application\ Support/ 目录下，删除ShadowsocksX-NG-R8和ShadowsocksX-NG文件夹
> > 然后再进入/Library/Application\ Support/目录下，删除ShadowsocksX-NG-R8和ShadowsocksX-NG文件夹
> > 再重新启动代理。
> > 服务器配置没问题的话，有很大可能是因为代理冲突了。ss-local进程有多个，抢占相同端口。
> 
> 是这两个文件夹吗？但是里面没有ng 的文件夹，只有r8的文件夹。
> <img alt="iShot2020-03-16下午12 10 25" width="806" src="https://user-images.githubusercontent.com/50537627/76722755-e1802280-677f-11ea-9d03-e9b7ac2659e8.png">
> <img alt="iShot2020-03-16下午12 10 15" width="806" src="https://user-images.githubusercontent.com/50537627/76722761-e6dd6d00-677f-11ea-8287-c1ad983a401e.png">

对，删掉之后再开1.4.9版本的

**Comment by horaynia** [comment]
> ```shell
> ```shell
> ```shell
> ```shell
> ```shell
> ss-local
> ```
> 
> 
> 你升级的是这个项目里的ss-local吗？
> https://github.com/shadowsocks/shadowsocks-libev
> 这个是项目只支持SS，不支持SSR，，我之前升级试过，加了SSR的协议和混淆数据会解密失败。
> 目前我找到最新的支持SSR的ss-local是：
> https://github.com/shadowsocksrr/shadowsocksr-libev
> 我也尝试升级过，但是效果不好。
> 目前我想到的方案是使用Python版本的SSR，然后使用pyinstaller打包成二进制文件，然后更新，但是那样一是需要导入很多附属文件，二是需要改动不少代码来调用，工作量较大。
> 大神，您的1.4.9的是没有安装包的吗？是需要别的方式安装吗？小白一个。可以打包个安装包吗？感谢
> https://github.com/paradiseduo/ShadowsocksX-NG-R8/releases/download/1.4.9/ShadowsocksX-NG-R.zip
> ```shell
> ```shell
> ```shell
> ss-local
> ```
> 
> 
> 你升级的是这个项目里的ss-local吗？
> https://github.com/shadowsocks/shadowsocks-libev
> 这个是项目只支持SS，不支持SSR，，我之前升级试过，加了SSR的协议和混淆数据会解密失败。
> 目前我找到最新的支持SSR的ss-local是：
> https://github.com/shadowsocksrr/shadowsocksr-libev
> 我也尝试升级过，但是效果不好。
> 目前我想到的方案是使用Python版本的SSR，然后使用pyinstaller打包成二进制文件，然后更新，但是那样一是需要导入很多附属文件，二是需要改动不少代码来调用，工作量较大。
> 大神，您的1.4.9的是没有安装包的吗？是需要别的方式安装吗？小白一个。可以打包个安装包吗？感谢
> https://github.com/paradiseduo/ShadowsocksX-NG-R8/releases/download/1.4.9/ShadowsocksX-NG-R.zip
> 安装完您的和wzdnzd大神的都出现了1个同样的问题，都无法爬墙。安装1.4.4就可以。难道是我的电脑有毒吗？😂。大神可以教教怎么解决吗？
> 先关闭代理
> 进入~/Library/Application\ Support/ 目录下，删除ShadowsocksX-NG-R8和ShadowsocksX-NG文件夹
> 然后再进入/Library/Application\ Support/目录下，删除ShadowsocksX-NG-R8和ShadowsocksX-NG文件夹
> 再重新启动代理。
> 服务器配置没问题的话，有很大可能是因为代理冲突了。ss-local进程有多个，抢占相同端口。
> 
> 是这两个文件夹吗？但是里面没有ng 的文件夹，只有r8的文件夹。
> 
> 
> 
> 对，删掉之后再开1.4.9版本的
> ```

可以了。感谢大神。还有就是您的下载的原地址是多少呢？这样我可以随时看看其更新情况，您刚给的，点击后直接下载了。看不到网址。

**Comment by paradiseduo** [comment]
> > ```shell
> > ```shell
> > ```shell
> > ```shell
> > ```shell
> > ss-local
> > ```
> > 
> > 
> > 你升级的是这个项目里的ss-local吗？
> > https://github.com/shadowsocks/shadowsocks-libev
> > 这个是项目只支持SS，不支持SSR，，我之前升级试过，加了SSR的协议和混淆数据会解密失败。
> > 目前我找到最新的支持SSR的ss-local是：
> > https://github.com/shadowsocksrr/shadowsocksr-libev
> > 我也尝试升级过，但是效果不好。
> > 目前我想到的方案是使用Python版本的SSR，然后使用pyinstaller打包成二进制文件，然后更新，但是那样一是需要导入很多附属文件，二是需要改动不少代码来调用，工作量较大。
> > 大神，您的1.4.9的是没有安装包的吗？是需要别的方式安装吗？小白一个。可以打包个安装包吗？感谢
> > https://github.com/paradiseduo/ShadowsocksX-NG-R8/releases/download/1.4.9/ShadowsocksX-NG-R.zip
> > ```shell
> > ```shell
> > ```shell
> > ss-local
> > ```
> > 
> > 
> > 你升级的是这个项目里的ss-local吗？
> > https://github.com/shadowsocks/shadowsocks-libev
> > 这个是项目只支持SS，不支持SSR，，我之前升级试过，加了SSR的协议和混淆数据会解密失败。
> > 目前我找到最新的支持SSR的ss-local是：
> > https://github.com/shadowsocksrr/shadowsocksr-libev
> > 我也尝试升级过，但是效果不好。
> > 目前我想到的方案是使用Python版本的SSR，然后使用pyinstaller打包成二进制文件，然后更新，但是那样一是需要导入很多附属文件，二是需要改动不少代码来调用，工作量较大。
> > 大神，您的1.4.9的是没有安装包的吗？是需要别的方式安装吗？小白一个。可以打包个安装包吗？感谢
> > https://github.com/paradiseduo/ShadowsocksX-NG-R8/releases/download/1.4.9/ShadowsocksX-NG-R.zip
> > 安装完您的和wzdnzd大神的都出现了1个同样的问题，都无法爬墙。安装1.4.4就可以。难道是我的电脑有毒吗？😂。大神可以教教怎么解决吗？
> > 先关闭代理
> > 进入~/Library/Application\ Support/ 目录下，删除ShadowsocksX-NG-R8和ShadowsocksX-NG文件夹
> > 然后再进入/Library/Application\ Support/目录下，删除ShadowsocksX-NG-R8和ShadowsocksX-NG文件夹
> > 再重新启动代理。
> > 服务器配置没问题的话，有很大可能是因为代理冲突了。ss-local进程有多个，抢占相同端口。
> > 是这两个文件夹吗？但是里面没有ng 的文件夹，只有r8的文件夹。
> > 对，删掉之后再开1.4.9版本的
> 
> 可以了。感谢大神。还有就是您的下载的原地址是多少呢？这样我可以随时看看其更新情况，您刚给的，点击后直接下载了。看不到网址。

https://github.com/paradiseduo/ShadowsocksX-NG-R8/releases/

**Comment by horaynia** [comment]
> ```shell
> ```shell
> ```shell
> ```shell
> ```shell
> ```shell
> ss-local
> ```
> 
> 
> 你升级的是这个项目里的ss-local吗？
> https://github.com/shadowsocks/shadowsocks-libev
> 这个是项目只支持SS，不支持SSR，，我之前升级试过，加了SSR的协议和混淆数据会解密失败。
> 目前我找到最新的支持SSR的ss-local是：
> https://github.com/shadowsocksrr/shadowsocksr-libev
> 我也尝试升级过，但是效果不好。
> 目前我想到的方案是使用Python版本的SSR，然后使用pyinstaller打包成二进制文件，然后更新，但是那样一是需要导入很多附属文件，二是需要改动不少代码来调用，工作量较大。
> 大神，您的1.4.9的是没有安装包的吗？是需要别的方式安装吗？小白一个。可以打包个安装包吗？感谢
> https://github.com/paradiseduo/ShadowsocksX-NG-R8/releases/download/1.4.9/ShadowsocksX-NG-R.zip
> ```shell
> ```shell
> ```shell
> ss-local
> ```
> 
> 
> 你升级的是这个项目里的ss-local吗？
> https://github.com/shadowsocks/shadowsocks-libev
> 这个是项目只支持SS，不支持SSR，，我之前升级试过，加了SSR的协议和混淆数据会解密失败。
> 目前我找到最新的支持SSR的ss-local是：
> https://github.com/shadowsocksrr/shadowsocksr-libev
> 我也尝试升级过，但是效果不好。
> 目前我想到的方案是使用Python版本的SSR，然后使用pyinstaller打包成二进制文件，然后更新，但是那样一是需要导入很多附属文件，二是需要改动不少代码来调用，工作量较大。
> 大神，您的1.4.9的是没有安装包的吗？是需要别的方式安装吗？小白一个。可以打包个安装包吗？感谢
> https://github.com/paradiseduo/ShadowsocksX-NG-R8/releases/download/1.4.9/ShadowsocksX-NG-R.zip
> 安装完您的和wzdnzd大神的都出现了1个同样的问题，都无法爬墙。安装1.4.4就可以。难道是我的电脑有毒吗？😂。大神可以教教怎么解决吗？
> 先关闭代理
> 进入~/Library/Application\ Support/ 目录下，删除ShadowsocksX-NG-R8和ShadowsocksX-NG文件夹
> 然后再进入/Library/Application\ Support/目录下，删除ShadowsocksX-NG-R8和ShadowsocksX-NG文件夹
> 再重新启动代理。
> 服务器配置没问题的话，有很大可能是因为代理冲突了。ss-local进程有多个，抢占相同端口。
> 是这两个文件夹吗？但是里面没有ng 的文件夹，只有r8的文件夹。
> 对，删掉之后再开1.4.9版本的
> 
> 可以了。感谢大神。还有就是您的下载的原地址是多少呢？这样我可以随时看看其更新情况，您刚给的，点击后直接下载了。看不到网址。
> 
> https://github.com/paradiseduo/ShadowsocksX-NG-R8/releases/
> ```

再次感谢大神。感谢大神的详细解答
