### ISSUE TITLE
找不到更新版本

### ISSUE THREAD

**Issue by Nirnturt** [wzdnzd/ShadowsocksX-NG-R#33]
近几天一直在弹窗提示更新1.5.1版本，点击**前往下载**之后在releases找不到这个所谓1.5.1版本，这算是bug吗？
![image](https://user-images.githubusercontent.com/26437323/77038245-3de87980-69ee-11ea-8a8f-aec62cbeacf3.png)

**Comment by paradiseduo** [comment]
1.5.1版本在这里
https://github.com/paradiseduo/ShadowsocksX-NG-R8/releases

**Comment by wzdnzd** [comment]
@paradiseduo 老哥要不在你维护的版本的订阅功能里加个过滤条件，然后我也就懒得折腾我这个repo了😂
