### ISSUE TITLE
显示网速选项存在内存泄漏

### ISSUE THREAD

**Issue by appdev** [wzdnzd/ShadowsocksX-NG-R#34]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.15.3
- Shadowsocksx-NG-R 1.4.9（1）

**Expected behavior:**

打开显示网速选项后，电脑变得很卡，32G内存很快用完，并且产生了30多G的缓存文件，查看进程，产生了几百个`nettop`进程。猜测是通过不断执行`nettop`命令，两次数据相减来获得当前网速的。但是执行完`nettop`后没有退出`nettop`造成的内存泄漏

**Comment by appdev** [comment]
![image](https://user-images.githubusercontent.com/9107717/77131036-1698b780-6a95-11ea-8c00-9a26af88f28c.png)

**Comment by fbion** [comment]
mark

**Comment by paradiseduo** [comment]
该问题已修复
https://github.com/paradiseduo/ShadowsocksX-NG-R8/releases
