### ISSUE TITLE
1.4.9版本无法打开

### ISSUE THREAD

**Issue by chingxuds** [wzdnzd/ShadowsocksX-NG-R#36]
RT，新发布的1.4.9版本下载后无法打开

**Comment by fbion** [comment]
ls ~/Library/Logs/DiagnosticReports/ShadowsocksX-NG_*.crash

**Comment by wzdnzd** [comment]
麻烦提供一下MacOS系统信息，谢谢

**Comment by chingxuds** [comment]
> 麻烦提供一下MacOS系统信息，谢谢

macOS 10.15.3 (19D76)

**Comment by wzdnzd** [comment]
理论上不应该会有问题，麻烦先按照这个方法试试：[https://github.com/wzdnzd/ShadowsocksX-NG-R/issues/32#issuecomment-599223189](https://github.com/wzdnzd/ShadowsocksX-NG-R/issues/32#issuecomment-599223189)

另外，可否描述一下你说的打不开是什么情况，提示信息或者报错界面截个图什么的

**Comment by fbion** [comment]
ls ~/Library/Logs/DiagnosticReports/ShadowsocksX-NG_*.crash

**Comment by chingxuds** [comment]
![截屏2020-03-24下午1 56 15](https://user-images.githubusercontent.com/3142486/77393139-6817ae00-6dd7-11ea-977e-77651251d844.png)
![截屏2020-03-24下午1 58 13](https://user-images.githubusercontent.com/3142486/77393372-dc525180-6dd7-11ea-9af9-11cc28ceada1.png)

@wzdnzd

**Comment by paradiseduo** [comment]
> ![截屏2020-03-24下午1 56 15](https://user-images.githubusercontent.com/3142486/77393139-6817ae00-6dd7-11ea-977e-77651251d844.png)
> ![截屏2020-03-24下午1 58 13](https://user-images.githubusercontent.com/3142486/77393372-dc525180-6dd7-11ea-9af9-11cc28ceada1.png)
> 
> @wzdnzd

https://www.jianshu.com/p/9c42e7656422

**Comment by chingxuds** [comment]
> > ![截屏2020-03-24下午1 56 15](https://user-images.githubusercontent.com/3142486/77393139-6817ae00-6dd7-11ea-977e-77651251d844.png)
> > ![截屏2020-03-24下午1 58 13](https://user-images.githubusercontent.com/3142486/77393372-dc525180-6dd7-11ea-9af9-11cc28ceada1.png)
> > @wzdnzd
> 
> https://www.jianshu.com/p/9c42e7656422

这个问题与安全限制不同，他不是无法校验应用的身份，而是直接不识别应用，即使关了安全校验也打不开

**Comment by wzdnzd** [comment]
@chingxuds 根据[少数派](https://sspai.com/post/52828)这里的信息来看 应该是解压缩过程中（猜测抑或是下载过程中）出了问题，你重新下载试试

**Comment by chingxuds** [comment]
> @chingxuds 根据[少数派](https://sspai.com/post/52828)这里的信息来看 应该是解压缩过程中（猜测抑或是下载过程中）出了问题，你重新下载试试

换了一个下载工具确实好了，提个建议，后续Release时附上校验文件，这样我们就可以自行校验下载是否正确了。
