### ISSUE TITLE
崩溃日志

### ISSUE THREAD

**Issue by BobOfRivia** [wzdnzd/ShadowsocksX-NG-R#37]
以下是崩溃日志，隔一两小时崩溃一次。colab的任务无法正常进行下去：

Process:               ShadowsocksX-NG [18782]
Path:                  /Users/USER/Documents/ShadowsocksX-NG-R.app/Contents/MacOS/ShadowsocksX-NG
Identifier:            com.qiuyuzhou.ShadowsocksX-NG
Version:               1.4.8 (1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           ShadowsocksX-NG [18782]
User ID:               --

Date/Time:             2020-03-31 09:56:03.172 +0800
OS Version:            Mac OS X 10.15.4 (19E266)
Report Version:        12
Bridge OS Version:     3.0 (14Y908)
Anonymous UUID:        9ECCF28F-C8BA-C57F-7A19-FE836365A929

Sleep/Wake UUID:       88399B5E-F476-4DFD-8679-7C1144EA86C0

Time Awake Since Boot: 27000 seconds
Time Since Wake:       4300 seconds

System Integrity Protection: enabled

Crashed Thread:        1

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Failed to set posix_spawn_file_actions for fd -1 at index 0 with errno 9'
abort() called
terminating with uncaught exception of type NSException

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff31fd1d07 __exceptionPreprocess + 250
1   libobjc.A.dylib                     0x00007fff6acf65bf objc_exception_throw + 48
2   Foundation                          0x00007fff3468e0c4 -[NSConcreteTask launchWithDictionary:error:] + 5316
3   ShadowsocksX-NG                     0x000000010e77a2ca ShadowsocksX-NG + 58058
4   ShadowsocksX-NG                     0x000000010e77a558 ShadowsocksX-NG + 58712
5   Foundation                          0x00007fff346473ca __NSFireTimer + 67
6   CoreFoundation                      0x00007fff31f709b9 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
7   CoreFoundation                      0x00007fff31f7051f __CFRunLoopDoTimer + 859
8   CoreFoundation                      0x00007fff31f70007 __CFRunLoopDoTimers + 322
9   CoreFoundation                      0x00007fff31f54daa __CFRunLoopRun + 1871
10  CoreFoundation                      0x00007fff31f53ffe CFRunLoopRunSpecific + 462
11  Foundation                          0x00007fff345e82a8 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
12  Foundation                          0x00007fff3469ad2f -[NSRunLoop(NSRunLoop) run] + 76
13  ShadowsocksX-NG                     0x000000010e77a188 ShadowsocksX-NG + 57736
14  Foundation                          0x00007fff345e0882 __NSThread__start__ + 1064
15  libsystem_pthread.dylib             0x00007fff6c0a2109 _pthread_start + 148
16  libsystem_pthread.dylib             0x00007fff6c09db8b thread_start + 15

**Comment by wzdnzd** [comment]
看你使用的版本是Version: 1.4.8 (1) ，建议先升级到最新版本试试，如果还是crash，请提供更详细的日志，谢谢

**Comment by BobOfRivia** [comment]
好的，谢谢，我更新一下再用～
