### ISSUE TITLE
建议增加服务负载均衡功能

### ISSUE THREAD

**Issue by geminird** [wzdnzd/ShadowsocksX-NG-R#38]
建议像Windows版一样，增加多个服务负载均衡功能，自动或手动选择其中几个服务器。

**Comment by wzdnzd** [comment]
目前如果开启自动延迟测试的话，默认10分钟测一次，然后选择延迟最低的节点做代理，算是某种意义上的“负载均衡”吧，当然，不一定能达到复杂均衡的效果，看节点之间是不是某个节点有绝对优势

负载均衡这个 暂时不考虑

**Comment by geminird** [comment]
> 目前如果开启自动延迟测试的话，默认10分钟测一次，然后选择延迟最低的节点做代理，算是某种意义上的“负载均衡”吧，当然，不一定能达到复杂均衡的效果，看节点之间是不是某个节点有绝对优势
> 
> 负载均衡这个 暂时不考虑


您好，多谢您的耐心答复。其实，延迟低并不代表服务器下载带宽高以及稳定性好，程序自动化的东西有的时候还是不能满足用户的使用体验，所以增加让用户选择选中多个服务器，客户端可以从这几个服务器同时获取数据，体验会更好。可以去使用一下Windows版本的程序，有一定的优势。
