### ISSUE TITLE
能否加入负载均衡的功能?

### ISSUE THREAD

**Issue by miku1958** [wzdnzd/ShadowsocksX-NG-R#4]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.14.6
- Shadowsocksx-NG-R8  1.4.4-R8 (1)

Windows版的客户端( https://github.com/shadowsocksrr/shadowsocksr-csharp/ )有这个功能, 一般通过订阅能拿到很多服务器, 如果有负债均衡的话的确会好用很多, 可否考虑加入这个功能?

**Comment by paradiseduo** [comment]
可以看一下这个 https://github.com/paradiseduo/ShadowsocksX-NG-R8
负载均衡功能没有什么意思，会造成IP一直在变，容易导致各种账号被封
