### ISSUE TITLE
请问您维护的这版有快捷键支持么？

### ISSUE THREAD

**Issue by zcyh147** [wzdnzd/ShadowsocksX-NG-R#42]
- Shadowsocksx-NG 1.5.0-build6

网上搜索了一圈，发现之前提过的快捷键全都用不了，系统里面自己设置也不行，所以过来一问，感谢兄弟回答！

**Comment by wzdnzd** [comment]
目前没有快捷键，因为这个不是刚需，代理模式频繁切换不是常态

**Comment by zcyh147** [comment]
> 目前没有快捷键，因为这个不是刚需，代理模式频繁切换不是常态

多谢您回复，这功能切换的特频繁哈哈哈就琢磨弄个自动化，试了下 AppleScript 似乎也不支持，看来无解了……

**Comment by paradiseduo** [comment]
> > 目前没有快捷键，因为这个不是刚需，代理模式频繁切换不是常态
> 
> 多谢您回复，这功能切换的特频繁哈哈哈就琢磨弄个自动化，试了下 AppleScript 似乎也不支持，看来无解了……

目前应该没有全局快捷键的方法（在不点击激活APP的情况下就能响应快捷键，理由很简单，很多APP的快捷键是一样的），因此既然都要点击激活APP了，本身切换代理就在一级菜单，那么快捷键存在的意义就不大了。。

**Comment by likecreep** [comment]
> > > 目前没有快捷键，因为这个不是刚需，代理模式频繁切换不是常态
> > 
> > 
> > 多谢您回复，这功能切换的特频繁哈哈哈就琢磨弄个自动化，试了下 AppleScript 似乎也不支持，看来无解了……
> 
> 目前应该没有全局快捷键的方法（在不点击激活APP的情况下就能响应快捷键，理由很简单，很多APP的快捷键是一样的），因此既然都要点击激活APP了，本身切换代理就在一级菜单，那么快捷键存在的意义就不大了。。

请问您维护的版本和这个版本是什么关系呢 google出来三个shadowsocks-X-NG-R，有点懵

**Comment by paradiseduo** [comment]
都是从qinyuhang的版本切出来的分支，主要功能都一样，只有一些小的功能点不同。看个人喜好了。

**Comment by paradiseduo** [comment]
> > > > 目前没有快捷键，因为这个不是刚需，代理模式频繁切换不是常态
> > > 
> > > 
> > > 多谢您回复，这功能切换的特频繁哈哈哈就琢磨弄个自动化，试了下 AppleScript 似乎也不支持，看来无解了……
> > 
> > 
> > 目前应该没有全局快捷键的方法（在不点击激活APP的情况下就能响应快捷键，理由很简单，很多APP的快捷键是一样的），因此既然都要点击激活APP了，本身切换代理就在一级菜单，那么快捷键存在的意义就不大了。。
> 
> 请问您维护的版本和这个版本是什么关系呢 google出来三个shadowsocks-X-NG-R，有点懵

都是从qinyuhang的版本切出来的分支，主要功能都一样，只有一些小的功能点不同。看个人喜好了。

**Comment by DraculaPrince** [comment]
> > > > > 目前没有快捷键，因为这个不是刚需，代理模式频繁切换不是常态
> > > > 
> > > > 
> > > > 多谢您回复，这功能切换的特频繁哈哈哈就琢磨弄个自动化，试了下 AppleScript 似乎也不支持，看来无解了……
> > > 
> > > 
> > > 目前应该没有全局快捷键的方法（在不点击激活APP的情况下就能响应快捷键，理由很简单，很多APP的快捷键是一样的），因此既然都要点击激活APP了，本身切换代理就在一级菜单，那么快捷键存在的意义就不大了。。
> > 
> > 
> > 请问您维护的版本和这个版本是什么关系呢 google出来三个shadowsocks-X-NG-R，有点懵
> 
> 都是从qinyuhang的版本切出来的分支，主要功能都一样，只有一些小的功能点不同。看个人喜好了。

大佬，能不能给说下，这几个版本都是什么区别啊？
