### ISSUE TITLE
希望支持终端命令行模式

### ISSUE THREAD

**Issue by L1cardo** [wzdnzd/ShadowsocksX-NG-R#6]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.15 beta
- Shadowsocksx-NG 1.4.6-R8 (1)

希望加入终端命令行模式，[原版](https://github.com/shadowsocks/ShadowsocksX-NG)支持的，但是它不支持ssr

**Comment by paradiseduo** [comment]
这个功能已经加上  https://github.com/paradiseduo/ShadowsocksX-NG-R8

**Comment by ouyangmland** [comment]
> 这个功能已经加上 https://github.com/paradiseduo/ShadowsocksX-NG-R8

冒昧问一句，你这个可以打包生成dmg文件吗？我比较小白，不知道如何用你的源码安装。最近才开始用mac os

**Comment by paradiseduo** [comment]
> > 这个功能已经加上 https://github.com/paradiseduo/ShadowsocksX-NG-R8
> 
> 冒昧问一句，你这个可以打包生成dmg文件吗？我比较小白，不知道如何用你的源码安装。最近才开始用mac os

从APP Store下载Xcode，然后将工程git clone到本地，用xcode打开ShadowsocksX-NG.xcworkspace文件，然后点击左上角运行按钮即可。

**Comment by L1cardo** [comment]
> 这个功能已经加上 https://github.com/paradiseduo/ShadowsocksX-NG-R8

OK  谢谢啦

**Comment by ouyangmland** [comment]
> > > 这个功能已经加上 https://github.com/paradiseduo/ShadowsocksX-NG-R8
> > 
> > 
> > 冒昧问一句，你这个可以打包生成dmg文件吗？我比较小白，不知道如何用你的源码安装。最近才开始用mac os
> 方法
> 从APP Store下载Xcode，然后将工程git clone到本地，用xcode打开ShadowsocksX-NG.xcworkspace文件，然后点击左上角运行按钮即可。

感谢告知
