### ISSUE TITLE
macos 10.15下开启一段时间后会导致CPU占用过高

### ISSUE THREAD

**Issue by chingxuds** [wzdnzd/ShadowsocksX-NG-R#9]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.15 (19A602)
- Shadowsocksx-NG-R8 1.3.6-r8

**Expected behavior:**

正常运行

**Actual behavior:**

CPU占用过高，查看进程发现大量nettop命令被执行
<img width="1680" alt="Snipaste_2019-10-26_16-20-20" src="https://user-images.githubusercontent.com/3142486/67616566-2de8b700-f80d-11e9-92e8-a521effb3007.png">

**Steps to reproduce:**

打开一段时间后（约半小时左右）

**How often does this happen?**

每次

**ss-local.log**

[ss-local.log](https://github.com/wzdnzd/ShadowsocksX-NG-R/files/3774602/ss-local.log)

**Application log**

没有找到

**Comment by fsh905** [comment]
我也碰到了同样的问题, swap分区被占满了, 然后系统疯狂弹窗提示内存不足

**Comment by serpmelon** [comment]
我这里也遇到了, CPU跑满了
